---
title: "The Buffet Bet - Basket of Funds vs. All Passive"
subtitle: "Stats 107 Project Proposal"
author: "Banti Modi, David Wihl"
date: "November 16, 2016"
output:  pdf_document
linkcolor: blue
abstract: |
  Ten years ago, Warren Buffett made a famous bet: the ultimate passive investment, the Vanguard S&P 500 Index Fund Admiral (VFIAX), vs. a basket of funds determined by a team of hedge fund experts. Whoever had a lower return after ten years would donate $1 million to the charity of choice of the winner. After eight years, it looks increasingly likely that Buffett will win the bet.
---
\begin{center}
\textbf{Type: Simulating a trading strategy.}
\end{center}

## Can a basket of funds beat the market in long term?

Our project aims to create a Mutual Fund selector for semi-passive investor. A typical Vanguard customer may have to choose from over one hundred mutual funds without any guidance. We will create a portfolio to maximize returns over the long term using several trading strategies, two of which are listed below. In order to make this more realistic, we will take into account fees and transaction costs. Since this is aimed at a typical Vanguard retail customer, no shorting will be allowed. 

We will not account for taxes on the assumption that the funds are in a tax deferred account such as 401(k) or
IRA. For this reason, we will not evaluate ETFs which are at a disadvantage in a tax deferred account.

The portfolio will start with $100,000, which is the current average 401(k) balance 
(\href{http://time.com/money/4357248/retirement-401k-vanguard-balance/}{source}).

The overall time period will be evaluated on a twenty year history, or the maximum history of the security, whichever is shorter. 

The baseline or benchmark will be investing the same amount in VFIAX and leaving it 
there for the duration. 

 We will simulate whether rebalancing on a monthly, quarterly, semi-annual or annual basis is the best strategy.

## Initial Trading Strategies to be Attempted:

#### 1. Periodic Weight Balancing 

Under the epithet “volatility harvesting”, Bouchey et al (2012) draw attention to the impact of volatility on the compound growth rate (or geometric mean return) of periodically rebalanced
portfolios. We will try to use this strategy by selecting mutual funds 3 each from growth and value style - Large Cap, Mid Cap, Small cap. 

####2. Periodic weight balancing with style switching:

As observed in \href {https://www.cxoadvisory.com/4068/value-premium/measuring-the-value-premium-with-style-etfs/#more-4068} {Measuring Value Premium} investors tend to dump value in favor of growth during October-November and revert to value in December. To use this strategy, We will start with 3 mutual funds large, medium and small in value style,  on last day of September, we will sell them all and switch to Growth funds. We will again switch to  value funds at the end of November. we will be rebalancing as in first strategy within whichever style we are. At minimum, the following mutual funds will be selected in each category: 


Mkt Cap   | Value         | Growth
----- | ------------- | -------------
Large | VUVLX         | VWUSX
Mid   | VCVLX         | VMGRX 
Small | VBR           | VBK 


## References and Data Sources

* List of Vanguard funds, including fees and transaction costs, supplied by Vanguard https://investor.vanguard.com/mutual-funds/list#/mutual-funds/asset-class/month-end-returns
* The Buffet Bet, http://longbets.org/362/
* Fortune, The Buffett Bet http://fortune.com/2016/05/11/warren-buffett-hedge-fund-bet/

