---
title: "The Buffet Bet - Basket of Funds vs. All Passive"
subtitle: "Stats 107 Final Project"
author: "David Wihl"
date: "December 6, 2016"
abstract: |
  Ten years ago, Warren Buffett made a famous : the ultimate passive investment, the Vanguard S&P 500 Index Fund Admiral (VFIAX), vs. a basket of funds determined by a team of hedge fund experts. Whoever had a lower return after ten years would donate $1 million to the charity of choice of the winner. After eight years, it looks increasingly likely that Buffett will win the bet.
output: pdf_document
---
\begin{center}
\textbf{Type: Simulating a trading strategy.}
\end{center}

```{r echo=FALSE}
# Code goes here
```

# Introduction

# Methods

## Importing List of Vanguard Mutual Funds
```{r, message=FALSE, warning=FALSE}
loadRData = function(filename) {
  # Source: http://stackoverflow.com/questions/5577221/how-can-i-load-an-object-into-a-variable-name-that-i-specify-from-an-r-data-file
  load(filename)
  get(ls()[ls()!="filename"])
}
library(quantmod)
fromDate = "1996-12-01"
toDate   = "2016-10-31"
funds    = read.csv("data/vanguard.csv",header = T, stringsAsFactors = F)
# Load from previously cached download
stockDataEnv= loadRData("data/stockData.RData")
fundData = mget(funds$Ticker,stockDataEnv)

```

# Results

# Conclusions and Discussions

# References

This entire project code including source data can be found on GitHub ([https://github.com/wihl/stats107-project](https://github.com/wihl/stats107-project))



# Appendix A

The following is the code used to prepare this report:
```{r code=readLines(knitr::purl('writeup.Rmd', documentation = 0)), eval = FALSE}

```


